docs: adicionado seção para tags, na documentação
levxyca/diciotech pull request #111
Opened 2023-10-19 14:44 UTC by thiagofqs

Conforme as replies na issue #80 e no PR #38, foi discutido alguns pontos cruciais como regras e requisitos a serem seguidos nos futuros e existentes termos do projeto. Como citado de forma mais detalhada na issue #91, muitos "erros" ocorrem em alguns PRs de implementação de novos termos com uma tag atribuída, como: duplicações, tags que não batem com o conceito do termo, tags de linguagens de programação, etc.

Então, para manter uma maior organização e estabilidade do Diciotech, foi acrescentado uma nova seção na documentação do projeto, apenas para as tags, com o título de "**Adicionando uma nova tag no Diciotech**". Além disso, alguns erros de pontuação, presentes na documentação, foram corrigidos e alguns poucos textos alterados.

2023-10-24 20:15 UTC, levxyca requested changes
Obrigada por contribuir 🤩 Adicionei alguns comentários, veja o que acha! Em sua maioria, eu tentei tirar termos/palavras que fosse muito "autoritarias", eu sinto que isso assusta um pouco pessoas que ainda não se sentem 100% confortáveis a contribuir, pois ter várias regras e etc pode parecer algo complexo. No mais, conforme forem vindo novos pr's, a ideia também é ir educando essas pessoas para seguir essas boas práticas.

2023-10-24 20:15 UTC, levxyca commented on CONTRIBUTING.md
> +Antes de abrir o pull request, algumas **regras** e **requisitos** devem ser seguidos para uma maior organização e estabilidade do Diciotech.
Acho que podemos alterar um pouco, eu não sei se faz sentido, mas ter os termos regras e requisitos talvez assuster pessoas que sejam iniciantes e já estejam com medo de contribuir. O que você acha?

```suggestion
Antes de abrir o pull request, algumas **boas práticas** devem ser seguidas para uma maior organização e estabilidade do Diciotech.

```

2023-10-24 20:15 UTC, levxyca commented on CONTRIBUTING.md
> +- Um termo, de forma obrigatória, deve ser vinculado a, no mínimo, uma tag;
```suggestion
- Um termo, deve ser vinculado a, no mínimo, uma tag;

```

2023-10-24 20:15 UTC, levxyca commented on CONTRIBUTING.md
> +- Não pode haver duplicações de tags em um mesmo termo. Exemplo: `"tags": ["Conceito", "Conceito"]`;
```suggestion
- Evite duplicações de tags em um mesmo termo. Exemplo: `"tags": ["Conceito", "Conceito"]`;

```

2023-10-24 20:15 UTC, levxyca commented on CONTRIBUTING.md
> +- As tags atribuídas a um termo devem fazer total sentido com o mesmo.
```suggestion
- Tome a cuidado para que as tags atribuídas a um termo façam sentido com o mesmo.

```

2023-10-24 20:15 UTC, levxyca commented on CONTRIBUTING.md
> +Você pode contribuir com o projeto propondo uma nova tag e a apresentando, como sugestão, por meio de uma [issue](https://github.com/levxyca/diciotech/issues) para que se possa abrir uma discussão a
```suggestion
Você pode contribuir com o projeto propondo uma nova tag e a apresentando, como sugestão, por meio de uma [issue](https://github.com/levxyca/diciotech/issues) para que se possa abrir uma discussão a respeito, para uma futura adição através de pull request. As tags disponíveis **sempre** vão estar presentes nessa documentação.

```

2023-10-24 20:15 UTC, levxyca commented on CONTRIBUTING.md
> +Antes de criar uma issue e abrir um PR, todas as tags devem seguir algumas regras e requisitos:
```suggestion
Antes de criar uma issue e abrir um PR, todas as tags devem seguir algumas boas práticas:

```

2023-10-24 20:15 UTC, levxyca commented on CONTRIBUTING.md
> +- Não devem existir tags de linguagens de programação, bibliotecas e frameworks. Exemplo: JavaScript, C#, React.js.
Acho que essa linha não precisa, visto que o tópico anterior fala sobre a tags serem generalistas e categóricas.

2023-10-24 20:15 UTC, levxyca commented on README.md
> +Verifique o arquivo [ROADMAP.md](ROADMAP.md) para se manter atualizado de como o projeto deve evoluir.
Alterei visando deixar a liguagem mais neutra.

```suggestion
Verifique o arquivo [ROADMAP.md](ROADMAP.md) para se manter por dentro de como o projeto deve evoluir.
```

2023-10-25 10:31 UTC, thiagofqs commented
> Obrigada por contribuir 🤩 Adicionei alguns comentários, veja o que acha! Em sua maioria, eu tentei tirar termos/palavras que fosse muito "autoritarias", eu sinto que isso assusta um pouco pessoas que ainda não se sentem 100% confortáveis a contribuir, pois ter várias regras e etc pode parecer algo complexo. No mais, conforme forem vindo novos pr's, a ideia também é ir educando essas pessoas para seguir essas boas práticas.

Eu que agradeço por poder contribuir! 🫡
Li todas as suas considerações e sugestões e, realmente, tens total razão, principalmente com relação a certas palavras, que usei, que soam muito "autoritárias". Não parei para pensar sobre como poderia ser a reação de uma pessoa usuária com relação a ter um maior conforto para contribuir com o projeto. Além disso, obrigado por apontar como ser mais neutro nas palavras, as vezes tenho certa dificuldade com isso. Farei essas mudanças.

2023-10-25 11:04 UTC, thiagofqs commented
Prontinho, @levxyca! Realizei as alterações, mas como estava com muitos commits, acabei juntando tudo em um só.

2023-10-25 17:07 UTC, levxyca approved these changes

2023-10-25 17:07 UTC, merged