feat: Adiciona termos técnicos de DOM, Responsividade e SASS/SCSS
levxyca/diciotech pull request #115
Opened 2023-10-25 20:01 UTC by NeiltonSeguins

## Adição de Termos Técnicos no Frontend

Olá equipe do projeto,

Nesta pull request, adicionei três termos técnicos ao dicionário tech, na categoria Frontend. Os termos adicionados são:

- **DOM (Document Object Model)**

- **SASS/SCSS**

- **Responsividade**

Esses termos são importantes para iniciantes no desenvolvimento frontend e ajudarão a tornar o dicionário tech mais completo e informativo.

Ficarei feliz em fazer quaisquer ajustes ou esclarecimentos necessários. Obrigado por considerar esta contribuição!

Saudações,
[Neilton Seguins]

2023-10-27 17:52 UTC, levxyca requested changes
Obrigadap or contribuir ☺ deixei um comentário, veja o que acha!

2023-10-27 17:52 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Pré-processadores CSS que permitem a criação de estilos mais complexos e reutilizáveis. São formas mais avançadas de escrever estilos (cores, fontes) para sites.",
Eu acho que aqui poderia ser um pouquinho mais didático, que tal:

```suggestion
      "description": "Pré-processadores CSS são como ferramentas especiais que facilitam a criação de estilos para sites. Eles tornam possível fazer estilos mais complicados e que podem ser usados de novo em diferentes partes do site. Pense neles como formas mais espertas de escolher cores e fontes para tornar um site bonito e funcional..",
```

Outro ponto, isso seria a definição do que é um pré-processador, certo? Acho que se encaixaria mais do que colocar como SASS/SCSS, pois estem vários outros.

2023-11-02 16:27 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Pré-processadores CSS que permitem a criação de estilos mais complexos e reutilizáveis. São formas mais avançadas de escrever estilos (cores, fontes) para sites.",
@NeiltonSeguins quando você diz colocar como exemplo, se refere ao código em si ou só adicionar o nome desses pré-processadores como exemplo mesmo?

2023-11-09 22:55 UTC, NeiltonSeguins commented on assets/data/cards_pt-br.json
> +      "description": "Pré-processadores CSS que permitem a criação de estilos mais complexos e reutilizáveis. São formas mais avançadas de escrever estilos (cores, fontes) para sites.",
Só adicionar os nomes como exemplo mesmo no texto.

2023-11-26 15:53 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Pré-processadores CSS que permitem a criação de estilos mais complexos e reutilizáveis. São formas mais avançadas de escrever estilos (cores, fontes) para sites.",
Show @NeiltonSeguins! Só lembrando para olhar e atualizar o seu PR 🥹 não se esqueça de atualizar a branch também!

2023-12-05 15:10 UTC, NeiltonSeguins commented on assets/data/cards_pt-br.json
> +      "description": "Pré-processadores CSS que permitem a criação de estilos mais complexos e reutilizáveis. São formas mais avançadas de escrever estilos (cores, fontes) para sites.",
Oi, @levxyca ! Desculpa a demora em fazer essa alteração. Mas finalmente atualizei a branch e a PR conforme essa conversa. Pode revisar, por favor?

2023-12-05 15:15 UTC, NeiltonSeguins commented on assets/data/cards_pt-br.json
> +      "description": "Pré-processadores CSS são como ferramentas especiais que facilitam a criação de estilos para sites. Eles tornam possível fazer estilos mais complicados e que podem ser usados de
@levxyca Mudei o título para "Pré-processadores CSS" para se adequar a descrição e citei como exemplos o SASS/SCSS e o LESS que são os mais populares.

2024-01-22 20:50 UTC, levxyca approved these changes
Muito obrigada por fazer as alterações 😊 vou deixar seu PR aprovado, pode atualizar a sua branch, por favor? Aí já dou merge no seu PR.

2024-06-25 17:26 UTC, levxyca approved these changes

2024-06-25 17:27 UTC, merged