Remove duplication term.
levxyca/diciotech pull request #125
Opened 2023-10-29 12:44 UTC by ju-couto

2023-11-06 18:49 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "tags": ["Conceito", "Front-end", "Mobile"]
Aqui pode deixar só a tag de mobile.

2023-11-06 18:50 UTC, levxyca requested changes
Obrigada por contribuir, deixei um comentário 😊

2024-05-12 20:05 UTC, thiagofqs requested changes
Hey, Julia! Obrigado pela sua contribuição no projeto, deixei um comentário 😊

2024-05-12 20:05 UTC, thiagofqs commented on assets/data/cards_pt-br.json
> +      "tags": ["Conceito", "Mobile"]
Analisando as tags de outros frameworks já presentes no Diciotech, que constam no `cards_pt-br.json`, eles não possuem a tag "Conceito". Nesse caso, pode deixar apenas a tag "Mobile".

```suggestion
      "tags": ["Mobile"]
```

2024-06-25 18:04 UTC, levxyca approved these changes

2024-06-25 18:04 UTC, merged