adicionando termos: computação em nuvem, CORS e garbage collector
levxyca/diciotech pull request #134
Opened 2023-11-01 01:21 UTC by taernsietr

Adiciona os termos descritos no título.

Criando essa PR também para verificar se compreendi direito o workflow para contribuir com o projeto. Pretendo adicionar mais, se tudo correr bem :)

2024-05-12 20:54 UTC, thiagofqs requested changes
Hey, @taernsietr! Obrigado pelo sua contribuição 😉

A ideia do Diciotech é explicar os termos de forma simplificada para que, além das pessoas já desenvolvedoras, pessoas fora da área também possam entender os conceitos da melhor forma possível.

As explicações estão muito boas e foram objetivas! Apesar disso, creio que podemos simplificar mais e evitar jargões técnicos para podermos atingir todos os públicos.

Deixei algumas sugestões e não esqueça de atualizar a sua branch! Se preferir, você também pode fazer outras sugestões :)

2024-05-12 20:54 UTC, thiagofqs commented on assets/data/cards_pt-br.json
> +      "description": "Literalmente \"coletor de lixo\" em inglês, é um tipo de software auxiliar que é executado ao lado de uma aplicação principal, percebendo memória que foi alocada (designada ao p
Sugiro que expandamos um pouco mais a descrição para torná-la mais detalhada e acessível. Isso pode ajudar a esclarecer o conceito para quem não está familiarizado com ele. Abaixo, deixei uma sugestão de como podemos enriquecer o texto para tornar a explicação mais clara e compreensiva.

```suggestion
      "description": "Garbage collector, ou \"coletor de lixo\", é uma ferramenta que ajuda a liberar espaço na memória do computador automaticamente. Imagine que, ao desenvolver um programa, você use blocos de memória para guardar informações. Com o tempo, alguns desses blocos não são mais necessários. O coletor de lixo identifica esses blocos "inúteis" e os limpa, devolvendo o espaço para o sistema usar novamente. Isso é especialmente útil em linguagens de programação como Java, C# e JavaScript, onde esse processo é feito automaticamente, ajudando a evitar problemas e deixando o computador mais rápido.",
```

2024-05-12 20:54 UTC, thiagofqs commented on assets/data/cards_pt-br.json
> +      "description": "De modo geral, refere-se ao uso de computação disponível através da internet e abstraído do equipamento físico utilizado. É um conceito extremamente amplo, que compreende desde
Sugiro que possamos fazer uma versão simplificada que evita jargões técnicos e torna o conceito mais acessível.

```suggestion
      "description": "De modo geral, refere-se ao uso de serviços de computador, como armazenamento de arquivos e execução de programas, através da internet. Isso significa que você não precisa de equipamentos físicos, pois tudo é feito online. Você pode acessar seus dados e programas de qualquer lugar, a qualquer momento, sem se preocupar com a manutenção dos equipamentos físicos.",
```

2024-05-12 20:54 UTC, thiagofqs commented on assets/data/cards_pt-br.json
> +      "description": "Do inglês \"Cross-Origin Resource Sharing\", ou Compartilhamento de Recursos de Origem Cruzada, refere-se a um mecanismo que gere recursos web acessados a partir de outras págin
Gostaria de sugerir uma versão um pouco mais simplificada, que poderia ajudar especialmente as pessoas que estão começando a entender melhor este conceito. Segue minha sugestão:

```suggestion
      "description": "Do inglês \"Cross-Origin Resource Sharing\" ou, em português, \"Compartilhamento de Recursos de Origem Cruzada\", é uma regra de segurança para websites. Ele determina como recursos de uma página web podem ser acessados por outra página de um domínio diferente. Por exemplo, uma imagem ou arquivo CSS geralmente pode ser compartilhado entre diferentes sites sem problemas, mas códigos JavaScript frequentemente têm restrições mais rigorosas.",
```

2024-06-25 18:17 UTC, levxyca approved these changes

2024-06-25 18:17 UTC, merged