Adicionando Scrum e UML
levxyca/diciotech pull request #161
Opened 2024-03-16 23:43 UTC by daianercruz

2024-05-17 19:43 UTC, levxyca requested changes
Sua explicação está clara e didática 👏🏻 Obrigada pela contribuição! Só deixei apenas uma mudança ali para ser feita com relação as tags!

No mais, não se esqueça de atualizar a sua branch 🫰🏻 feito isso, podemos mergear 🚀

2024-05-17 19:43 UTC, levxyca commented on assets/data/cards_pt-br.json
>          "Back-end"
Aqui pode deixar somente a tag de `Back-end`.

```suggestion
        "Back-end"
```

2024-05-17 19:44 UTC, levxyca commented
Ah, @daianercruz se possível, nas próximas, crie uma issue para linkar a sua PR, isso nos ajuda a mapear o que está sendo feito e dá visibilidade para as outras pessoas colaboradores do projeto, evitando que mais de uma pessoa trabalhe em uma mesma feature, por exemplo 🫰🏻

2024-05-17 20:01 UTC, daianercruz commented
> Ah, @daianercruz se possível, nas próximas, crie uma issue para linkar a sua PR, isso nos ajuda a mapear o que está sendo feito e dá visibilidade para as outras pessoas colaboradores do projeto, evitando que mais de uma pessoa trabalhe em uma mesma feature, por exemplo 🫰🏻

2024-05-20 17:15 UTC, levxyca approved these changes

2024-05-20 17:15 UTC, merged