Adiciona templates de repositório (#92)
levxyca/diciotech pull request #169
Opened 2024-06-17 18:10 UTC by andrepg

Conforme #92, este PR sugere formatos básicos de modelos e formulário. As principais características consideradas foram a simplicidade e foco em informações importantes para resolução dos problemas propostos pela issue.

Assim, temos três modelos básicos para iniciar: o pedido de um novo verbete/termo, a solicitação de novos recursos e problemas/bugs que o usuário possa encontrar. Ainda há a possibilidade de “travar” issues em branco, que não foi implementada ~ainda~.

Sugestões na criação dos formulários e novas categorias são bem-vindas. Basta um ping e volto aqui para a discussão. 

Saudações a todos e parabéns pelo projeto inclusivo e de grande valor! 😄

2024-06-20 16:27 UTC, levxyca commented
@andrepg boa 🚀 vou revisar logo mais no final da tarde 🫰🏻

2024-06-20 20:50 UTC, levxyca requested changes
Obrigada por contribuir 🫰🏻 Deixei duas sugestões, mas coisas bem simples, pensando em melhorar a compreensão.

2024-06-20 20:50 UTC, levxyca commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: Forneça uma descrição completa do problema que enfrentado
```suggestion
      description: Forneça uma descrição completa do problema
```

2024-06-20 20:50 UTC, levxyca commented on .github/ISSUE_TEMPLATE/inclusao-de-verbete.md
Acho que aqui vale, além de verbete, adicionar "termo" para se alinhar com as comunicações que normalmente usamos.

2024-06-20 21:06 UTC, andrepg commented
@levxyca por coincidência estava tirando um tempo para mexer nos projetos aqui e pude resolver rápido ⚡

2024-06-21 13:11 UTC, levxyca approved these changes

2024-06-21 13:11 UTC, merged