Feat: adição dos termos DOS, DDOS, BOTNET's
levxyca/diciotech pull request #187
Opened 2024-09-12 12:35 UTC by joaovictor1516

## Descrição de PR

- Adição da descrição do ataque DOS, de Botnet  e do ataque DDOS, como os três assuntos se correlacionam achei mais coeso adicionar os assuntos na mesma PR .

### Issue relacionado

- #184 

## Motivações

- Com os recentes ataques aos sites do governo estes assuntos estão mais presentes na mídia.

2024-09-17 20:20 UTC, levxyca commented
@joaovictor1516 acho que deu algum problema na hora de reabrir o PR, ele tá dando changes em mais de 16 arquivos. Vou te sugerir para fechar essa PR, atualizar a branch principal e fazer o processo novamente, o que acha? Assim garantimos que fique tudo certinho! Se precisar de um help pode me chamar 🫰🏻

2024-09-18 19:53 UTC, levxyca reviewed
@joaovictor1516 deixei algumas sugestões, veja o que acha 💙

2024-09-18 19:53 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Uma botnet é uma rede de equipamentos infectados por um malware (malwares são softuares, tmabém conhecidos como programas, mal-intencionados) e controlados por um criminoso-cibe
Tenha algumas sugestões pensando em deixar o texto mais acessível para pessoas que não são da área tech, veja o que acha:

- Pode ser útil adicionar breves explicações para termos técnicos como "malware." Por exemplo, em vez de só mencionar "malware," podemos explicar que são programas maliciosos que afetam os dispositivos.
- Incorporar exemplos simples pode ajudar na compreensão. Por exemplo, ao falar sobre "IoT," podemos mencionar diretamente aparelhos como celulares, TVs inteligentes e lâmpadas conectadas à internet.
- Reduzir a complexidade das definições pode facilitar o entendimento. Por exemplo, ao explicar "DDOS," podemos descrever como um ataque onde muitos dispositivos tentam acessar um site ao mesmo tempo para sobrecarregá-lo.

2024-09-19 05:39 UTC, joaovictor1516 commented on assets/data/cards_pt-br.json
> +      "description": "Uma botnet é uma rede de equipamentos infectados por um malware (malwares são softuares, tmabém conhecidos como programas, mal-intencionados) e controlados por um criminoso-cibe
Ok, obrigado pelo feed back, vou tornar os textos mais acessíveis.

2024-09-19 12:18 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Uma botnet é uma rede de equipamentos infectados por um malware (malwares são softuares, tmabém conhecidos como programas, mal-intencionados) e controlados por um criminoso-cibe
@joaovictor1516 qualquer ajuda que precisar pode me chamar 🫰🏻

2024-09-20 12:14 UTC, levxyca requested changes
Tá ótimo agora @joaovictor1516, thanks 😊🫰🏻 Deixei só alguns ajustezinhos de digitação mesmo, feito isso, tá aprovado!

2024-09-20 12:14 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Botnet é uma rede de dispositivos conectadoas na internet infectados por um malware (Os malwares são programas malicioso que afetam dispositivo), possibilitando que criminosos-c
```suggestion
      "description": "Botnet é uma rede de dispositivos conectados na internet infectados por um malware (os malwares são programas maliciosos que afetam um dispositivo), possibilitando que criminosos-ciberneticos derrubem sites usando essa rede de dispositivos. Os dispositivos pedem ser desde um computador até um equipamento IoT (um aparelho IoT é um equipamento conectado à internet sem o uso de cabos, por exemplo: TVs inteligentes, lampadas inteligentes, geladeiras inteligentes e celulares).",
```

2024-09-20 16:25 UTC, levxyca approved these changes
Perfeito, obrigada pela contribuição 💙🫰🏻

2024-09-20 16:28 UTC, merged