Adiciona os conceitos de frameworks frontend populares, como: Angular.js, Vue.js, Svelte e Next.js
levxyca/diciotech pull request #205
Opened 2024-10-06 15:18 UTC by NeiltonSeguins

## Descrição de PR

Nesta pull request, adicionei quatro novos termos ao dicionário tech, na categoria Frontend e Frameworks. Os termos adicionados são:

- Angular.js
- Next.js
- Svelte
- Vue.js
- Também adicionei a tag "Framework" no React como complemento a documentação.

### Issue relacionado

- #204 

## Motivações

Esses termos são importantes no desenvolvimento front-end e trata-se de frameworks muito populares na comunidade, daí a importância de constar no dicionário tech. Acredito que será de grande ajuda para iniciantes que ouvem falar mas não sabem o conceito ou significado de cada termo.

### Informações adicionais

Ficarei feliz em fazer quaisquer ajustes ou esclarecimentos necessários. Obrigado por considerar esta contribuição!

Saudações,
Neilton

2024-10-14 22:25 UTC, levxyca requested changes
Olá @NeiltonSeguins! Obrigada pela sua contribuição 💙 Deixei algumas sugestões visando deixar as explicações mais didáticas e acessiveis. Veja o que acha!

2024-10-14 22:25 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Angular.js é um framework JavaScript criado pelo Google para desenvolver aplicações de página única (SPAs). Possui uma arquitetura robusta baseada em módulos e injeção de depend
Usei termos mais simples e adicionei uma explicação sobre SPAs para deixar mais claro para quem não está familiarizado com o conceito. O que acha?

```suggestion
      "description": "Angular.js é uma ferramenta desenvolvida pelo Google que facilita a criação de sites ou aplicativos que funcionam como uma única página (SPAs), ou seja, sem recarregar a página inteira a cada interação. Ele organiza o código de forma eficiente usando "módulos" e "injeção de dependências", o que ajuda a manter tudo mais fácil de gerenciar. Grandes empresas como Google e Microsoft utilizam essa tecnologia."
```

2024-10-14 22:25 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Next.js é um framework baseado em React que facilita a criação de sites com renderização no servidor (SSR) e geração de páginas estáticas (SSG), proporcionando melhor SEO e carr
Simplifiquei alguns termos técnicos e expliquei brevemente os benefícios do SSR e SSG. O que acha?

```suggestion
      "description": "Next.js é uma ferramenta baseada no React que ajuda a criar sites mais rápidos e fáceis de encontrar nos buscadores (SEO). Ele permite que as páginas sejam geradas no servidor (SSR) ou criadas de forma estática (SSG), o que melhora o tempo de carregamento das páginas e a experiência da pessoa usuária."
```

2024-10-14 22:25 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Svelte é um framework JavaScript que compila o código em tempo de build, eliminando a necessidade de uma camada extra no navegador, o que o torna mais eficiente e leve em compar
Simplifiquei a explicação sobre a "compilação em tempo de build" e o impacto no desempenho. O que acha?

```suggestion
      "description": "Svelte é uma ferramenta JavaScript que transforma o código durante a construção do site ou aplicativo, sem precisar de uma camada extra para funcionar no navegador. Isso o torna mais rápido e leve em comparação com outras ferramentas similares."
```

2024-10-14 22:25 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Vue.js é um framework JavaScript para criar interfaces de usuário. Ele é progressivo, fácil de integrar em projetos e muito utilizado para construir aplicações de página única (
Deixei o termo "progressivo" mais implícito, focando na facilidade de integração e no uso em SPAs. O que acha?

```suggestion
      "description": "Vue.js é uma ferramenta JavaScript usada para criar interfaces de usuário, ou seja, o que as pessoas veem e interagem em um site ou aplicativo. Ele é fácil de adicionar a projetos já existentes e é muito utilizado para construir sites que funcionam como uma única página (SPAs)."
```

2024-10-14 23:43 UTC, NeiltonSeguins commented
Perfeito, @levxyca! Muito obrigado pelas sugestões. Eu li e aprovei todas, já fiz os commits também. Eu usei alguns termos técnicos e tentei resumir bem os conceitos. Mas sua revisão deixa as explicações melhores e facilita o entendimento para qualquer pessoa. 

Grande abraço

2024-10-17 11:56 UTC, levxyca approved these changes
Perfeito @NeiltonSeguins 💙 Obrigada pela contribuição!

2024-10-17 11:57 UTC, merged