Novos termos
levxyca/diciotech pull request #210
Opened 2024-10-09 14:58 UTC by ayrtton

## Inclusão de novos termos

Olá, neste pull request adicionei novos termos, sendo eles AIoT, Cidades Inteligentes, IoT e TI Verde.

2024-10-15 14:15 UTC, levxyca requested changes
Obrigada pela sua contribuição @ayrtton 💙 Deixei dois comentários com sugestões, me diga o que acha!

2024-10-15 14:15 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "AIoT (Artificial Intelligence of Things), ou Inteligência Artificial das Coisas, constitui a combinação entre Inteligência Artificial e Internet das Coisas. Um de seus principai
Deixei um pouco mas direto e didático aqui, o que acha?

```suggestion
      "description": "AIoT (Artificial Intelligence of Things), ou Inteligência Artificial das Coisas, é a combinação de Inteligência Artificial (IA) com a Internet das Coisas (IoT). Seu principal objetivo é automatizar e acelerar o processamento dos dados gerados pelos dispositivos de IoT, com o mínimo de intervenção humana. Isso facilita a análise dos dados e torna a tomada de decisões mais rápida. Sem a IA, embora houvesse um grande volume de informações disponíveis, seria necessário depender da intervenção humana para torná-las úteis."
```

2024-10-15 14:15 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Cidades Inteligentes (Smart Cities), são localidades cuja infraestrutura dispõe de organização urbana e aparatos digitais voltados à otimização de seus processos. Para tanto, é
O que acha dessa sugestão? Tentei deixar um pouco mais direto e fluido.

```suggestion
      "description": "Cidades Inteligentes (Smart Cities) são localidades que utilizam infraestrutura urbana organizada e tecnologias digitais para otimizar seus processos. Isso inclui o uso de dispositivos com Inteligência Artificial e Internet das Coisas, entre outros."
```

2024-10-16 21:46 UTC, ayrtton commented on assets/data/cards_pt-br.json
> +      "description": "AIoT (Artificial Intelligence of Things), ou Inteligência Artificial das Coisas, constitui a combinação entre Inteligência Artificial e Internet das Coisas. Um de seus principai
Acho que ficou melhor, obrigado 🌱

2024-10-18 16:41 UTC, levxyca commented
@ayrtton tu consegue atualizar sua branch e resolver os conflitos? Se precisar de ajuda pode me chamar 🫰🏻

2024-10-19 15:41 UTC, ayrtton commented
> @ayrtton tu consegue atualizar sua branch e resolver os conflitos? Se precisar de ajuda pode me chamar 🫰🏻

Oi, acho que consegui resolver o conflito.
Você poderia verificar se agora deu certo?

2024-10-24 12:19 UTC, levxyca approved these changes

2024-10-24 12:20 UTC, levxyca commented
Tudo certinho agora @ayrtton 🫰🏻 Vou dar merge! Na próxima contribuição, vou pedir pra você criar uma issue, por favor, isso nos ajuda na organização do projeto, se precisar de ajuda, pode me chamar 😄

2024-10-24 12:20 UTC, merged

2024-10-24 21:06 UTC, ayrtton commented
> Tudo certinho agora @ayrtton 🫰🏻 Vou dar merge! Na próxima contribuição, vou pedir pra você criar uma issue, por favor, isso nos ajuda na organização do projeto, se precisar de ajuda, pode me chamar 😄

Ah entendi, obrigado ✌️