adição de novos termos e possivelmente 1 tag
levxyca/diciotech pull request #213
Opened 2024-10-13 18:05 UTC by ProgramadorVictor

Adicionei alguns novos termos e possivelmente uma tag que irei abrir a issue.
Termos: API Rest, Web Service, Design Pattern, API Stateful, API Stateless, Bearer, Token, JWT, XSS, CSRF, Laravel, PHP
Tags: Cybersecurity

2024-10-15 14:38 UTC, levxyca requested changes
Obrigada pela contribuição 💙 Deixei algumas sugestões de mudanças nos textos visando melhorar a compreensão dos termos técnicos, me diga o que acha!

2024-10-15 14:38 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "PHP é uma linguagem de programação executada do lado do servidor, muito utilizada no desenvolvimento web. Ao olhar bem para o 'PHP', se assemelha a um elefante."
```suggestion
      "description": "PHP é uma linguagem de programação executada do lado do servidor, muito utilizada no desenvolvimento web. Um detalhe curioso é que o mascote oficial do PHP é um elefante, frequentemente associado à linguagem."
```

2024-10-15 14:38 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "É um framework PHP que facilita o desenvolvimento de aplicações web, feito para artesãos da web. Oferece recursos como roteamento, ORM e suporte a testes."
```suggestion
      "description": "É um framework PHP, uma ferramenta que que facilita o desenvolvimento de aplicações web, feito para artesãos da web. Ele oferece recursos como roteamento, que ajuda a direcionar as solicitações dos usuários para as partes corretas do aplicativo; ORM (Mapeamento Objeto-Relacional), que simplifica a interação com bancos de dados, permitindo que pessoas desenvolvedoras trabalhem com dados como se fossem objetos; e suporte a testes, que facilita a verificação do funcionamento correto do aplicativo, garantindo que ele opere como esperado."
```

2024-10-15 14:38 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "JSON Web Token é um método autenticação para transmissão de informações entre APIs, sendo uma das principais formas de autenticação em serviços web."
```suggestion
      "description": "JSON Web Token é um método autenticação para transmissão de informações entre APIs. É uma das principais formas de autenticação utilizadas em serviços web, permitindo que usuários se identifiquem e acessem recursos de forma segura."
```

2024-10-15 14:38 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Uma pessoa que possui um token de autenticação é chamada de Bearer. Esse tipo de token confere acesso a recursos protegidos e é amplamente utilizado em API Stateless."
```suggestion
      "description": "Uma pessoa que possui um token de autenticação é chamada de Bearer. Esse tipo de token confere acesso a recursos protegidos e é amplamente utilizado em API Stateless, onde a autenticação e as informações do usuário são mantidas no próprio token, em vez de em sessões no servidor."
```

2024-10-15 14:38 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Em uma API stateless, cada requisição é independente e contém todas as informações necessárias. O servidor não guarda estado entre as interações."
```suggestion
      "description": "Em uma API stateless, cada requisição é independente e contém todas as informações necessárias. O servidor não guarda estado entre as interações, o que significa que não armazena dados sobre as requisições anteriores."
```

2024-10-15 14:38 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Uma API stateful mantém informações do cliente entre as requisições, permitindo que o servidor acompanhe o estado da sessão."
```suggestion
      "description": "Uma API stateful mantém informações do cliente entre as requisições, permitindo que o servidor acompanhe o estado da sessão. Isso significa que o servidor pode lembrar dados sobre o cliente e suas interações anteriores, proporcionando uma experiência mais personalizada."
```

2024-10-15 14:38 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Design pattern é uma solução reutilizável para problemas comuns em desenvolvimento de software, facilitando a criação e manutenção de aplicações."
```suggestion
      "description": "Design pattern é uma solução reutilizável para problemas comuns em desenvolvimento de software, facilitando a criação e manutenção de aplicações. Esses padrões oferecem abordagens testadas e comprovadas, ajudando as pessoas desenvolvedoras a construirem sistemas de forma mais eficiente e organizada."
```

2024-10-15 14:38 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Um web service é um sistema que permite a comunicação entre diferentes aplicações pela internet, utilizando padrões como SOAP ou REST para troca de dados."
```suggestion
      "description": "Um web service é um sistema que permite a comunicação entre diferentes aplicações pela internet, utilizando padrões como SOAP ou REST para troca de dados. Esses serviços possibilitam que diferentes sistemas se conectem e compartilhem informações de forma eficiente, independentemente da linguagem de programação ou plataforma."
```

2024-10-15 14:38 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "API REST é uma forma de comunicação entre diferentes aplicações. É amplamente usada devido à sua simplicidade e facilidade de integração com aplicações web."
```suggestion
      "description": "API REST é uma forma de comunicação entre diferentes aplicações. É amplamente usada devido à sua simplicidade e facilidade de integração com aplicações web. Esse tipo de API permite que sistemas diferentes se conectem e troquem informações de maneira eficiente, utilizando os princípios do protocolo HTTP."
```

2024-10-15 21:07 UTC, ProgramadorVictor commented
As modificações estão ótimas, foi mal fazer você reescrever tudo 😢 ,  além do mais aparentemente o termo 'Cybersecurity' existe, o que eu devo fazer? Baixo os arquivos modificados e troco para 'Segurança cibernética' ai eu tenho que abrir outro PR?

2024-10-17 12:06 UTC, levxyca commented
@ProgramadorVictor foi mal nada, fique em tranquilidade, estou aqui pra ajudar mesmo 🫰🏻Você sabe atualizar a sua PR para fazer essas modificações? Você precisa ir na sua branch e atualizar os arquivos, isso vai refletir aqui no seu PR.

Se você não souber ou tiver dúvidas, eu posso te ajudar 😊

2024-10-17 19:09 UTC, ProgramadorVictor commented
Eu infelizmente não sei, pode ajudar?

2024-10-21 14:22 UTC, levxyca commented
@ProgramadorVictor, vou te dar um passo a passo bem macro aqui, e você pode me comunicar onde exatamente você tem dúvidas, pode ser?

1. Acesse a sua branch, aquela que você utilizou para abrir o PR.
2. Dê um `git pull` para garantir que tudo está atualizado.
3. Revise os comentários deixados na PR. Cada comentário contém uma sugestão específica ou uma melhoria a ser feita.
4. A partir das revisões dos comentários, você pode ir realizando as alterações. Você pode copiar e colar os textos novos diretamente.
5. Após finalizar os ajustes, faça o commit das alterações e dê um `git push` para atualizar sua branch, o que vai refletir nessas alterações aqui no seu PR.

2024-10-22 15:13 UTC, closed without merging

2024-10-24 12:25 UTC, levxyca commented
Aberta uma nova issue em https://github.com/levxyca/diciotech/pull/245