feat: create a button top
levxyca/diciotech pull request #242
Opened 2024-10-18 22:12 UTC by esterfania

## Descrição de PR

### Issue relacionado 

- #148

## Motivações

A motivação dessa alteração é contribuir com open source

### Informações adicionais

Essa PR adiciona um botão que retorna para o topo da página. Segue vídeo do comportamento:

![video-cortado](https://github.com/user-attachments/assets/04ce1b4d-d0d3-4a23-b98b-3c344d173056)

2024-10-22 18:02 UTC, george-gca commented on assets/sass/button_up.sass
> +    color: $white
Ao invés de usar `$white` e `$primary-500` diretamente, acho que é melhor já fazer pensando em possível valores diferentes para os temas. Exemplo:

Cor pro tema claro:

https://github.com/levxyca/diciotech/blob/b094b878854ea405c0dc87e35ca0214519611728/assets/sass/light_theme.sass#L8

Cor pro tema escuro:

https://github.com/levxyca/diciotech/blob/b094b878854ea405c0dc87e35ca0214519611728/assets/sass/dark_theme.sass#L8

Como usar a variável:

https://github.com/levxyca/diciotech/blob/b094b878854ea405c0dc87e35ca0214519611728/assets/sass/cookies.sass#L5

2024-10-22 18:02 UTC, george-gca commented on index.html
> +      Topo
Só uma opinião, será que é necessária a palavra `Topo`? Porque eu acho que só a setinha é suficiente, e caso a gente adicione outras línguas é mais um lugar pra adicionar um termo traduzido que acho que não é essencial

2024-10-23 11:53 UTC, levxyca commented
Obrigada pela revisão @george-gca!

2024-10-23 11:58 UTC, levxyca requested changes
@esterfania obrigada pela sua contribuição 🫰🏻 fico no aguardo nas respostas dos comentários

2024-10-23 11:58 UTC, levxyca commented on index.html
> +      Topo
@george-gca @esterfania minha única preocupação em não ter nenhum texto é que incluir a palavra "topo" pode ser mais claro para usuários menos familiarizados com ícones, mas acredito que como essa setinha pra voltar ao topo da página é bem comum, pode não ser um grande problema.

2025-04-24 11:56 UTC, levxyca commented
Oi, @esterfania 💙 Gostaria de entender se você ainda está disponível para trabalhar nesse PR?

2025-04-24 12:20 UTC, esterfania commented
> Oi, @esterfania 💙 Gostaria de entender se você ainda está disponível para trabalhar nesse PR?

Oi, sim! Vou fazer os ajustes do review entre hoje e amanhã

2025-04-25 13:06 UTC, george-gca commented
E vai manter escrito `topo`, ou ficar só uma setinha?

2025-04-25 13:07 UTC, levxyca commented
@esterfania @george-gca podemos manter só a setinha por enquanto, se tiver necessidade, atualizamos no futuro para ter a escrita também!

2025-04-25 23:29 UTC, closed without merging

2025-04-26 00:47 UTC, esterfania commented
Oi pessoal, abri outra PR com o ajuste: https://github.com/levxyca/diciotech/pull/309