Adicionando algumas hospedagens de Git
levxyca/diciotech pull request #249
Opened 2024-10-24 02:42 UTC by thenicolau

## Descrição de PR

Foi adicionado algumas hospedagens de git, como o GitLab, BitBucket e Aws Commit
### Issue relacionado

- #230 

## Motivações

### Informações adicionais

2024-10-24 15:29 UTC, george-gca requested changes

2024-10-24 15:29 UTC, george-gca commented on assets/data/cards_pt-br.json
> +      "description": "Assim como GitHub, o GitLab também é uma plataforma de hospedagem de código-fonte, mas além de versionar projetos como o GitHub, oferece ferramentas integradas de CI/CD (integra
O GitHub tem o GitHub actions que é integrado.

2024-10-24 15:29 UTC, george-gca commented on assets/data/cards_pt-br.json
> +      "description": "AWS Commit é a plataforma de hospedagem de código-fonte da Amazon(AWS),está totalmente integrado com o ecossistema AWS, permitindo fácil automação e integração com outros serviç
Faltou um espaço em `Amazon(AWS),está` e faltou . ao final da descrição.

2024-10-24 15:29 UTC, george-gca commented on assets/data/cards_pt-br.json
> +      "description": "Assim como GitHub, o BitBucket também é uma plataforma de hospedagem de código-fonte, mas se integra especialmente bem com ferramentas Atlassian, como o Jira, e suporta repositó
Faltou . ao final da descrição.

2024-11-01 16:59 UTC, george-gca requested changes

2024-11-01 16:59 UTC, george-gca commented on assets/data/cards_pt-br.json
> +      "description": "O GitHub é uma plataforma de hospedagem de código-fonte baseada na web que oferece uma variedade de serviços relacionados ao controle de versão e colaboração no desenvolvimento
Faltou um . final na descrição

2024-11-01 16:59 UTC, george-gca commented on assets/data/cards_pt-br.json
> +      "description": "Assim como GitHub, o GitLab também é uma plataforma de hospedagem de código-fonte, mas além de versionar projetos como o GitHub, oferece ferramentas integradas de CI/CD (integra
> mas além de versionar projetos como o GitHub, oferece ferramentas integradas de CI/CD

Como o GitHub e o [BitBucket](https://www.atlassian.com/br/software/bitbucket/features/pipelines) também fazem isso, não sei se essa parte ainda faz sentido. Talvez valha falar alguma outra coisa que ela tem de diferente, mas a única coisa de diferente que eu sei que tem é que vários códigos open source mudaram pro GitLab quando a Microsoft comprou o GitHub.

https://about.gitlab.com/blog/2018/05/31/welcome-gnome-to-gitlab/

https://about.gitlab.com/blog/2020/06/29/welcome-kde/

2024-11-07 21:55 UTC, george-gca requested changes
Acho que pode tirar a tag `Conceito` de todas essas ferramentas, afinal são ferramentas

2024-11-07 21:55 UTC, george-gca commented on assets/data/cards_pt-br.json
> +      "description": "AWS Commit é a plataforma de hospedagem de código-fonte da Amazon(AWS), está totalmente integrado com o ecossistema AWS, permitindo fácil automação e integração com outros servi
Faltou um espaço entre Amazon e AWS e acho que pode trocar a vírgula, tipo
`AWS Commit é a plataforma de hospedagem de código-fonte da Amazon (AWS) e está`

2024-11-07 21:55 UTC, george-gca commented on assets/data/cards_pt-br.json
> +      "description": "Assim como GitHub, o GitLab também é uma plataforma de hospedagem de código-fonte que assim como o GitHub, oferece ferramentas integradas de CI/CD (integração contínua e entrega
Trocar:

```
Assim como GitHub, o GitLab também é uma plataforma de hospedagem de código-fonte que assim como o GitHub,
```
por

```
Assim como GitHub, o GitLab também é uma plataforma de hospedagem de código-fonte baseada em Git que
```

2024-11-07 21:55 UTC, george-gca commented on assets/data/cards_pt-br.json
> +      "description": "Assim como GitHub, o GitLab também é uma plataforma de hospedagem de código-fonte que assim como o GitHub, oferece ferramentas integradas de CI/CD (integração contínua e entrega
Adicionar uma vírgula ali

...podem acessar e contruibir para seu código base`,` sendo muito mais...

e me pergunto também se a gente usa código base ou código fonte nesse caso

2024-11-07 21:55 UTC, george-gca commented on assets/data/cards_pt-br.json
> +      "description": "Assim como GitHub, o GitLab também é uma plataforma de hospedagem de código-fonte que assim como o GitHub, oferece ferramentas integradas de CI/CD (integração contínua e entrega
Mudar

```
que mantém seus códigos base fechado."
```

por

```
que mantêm seus códigos base fechados."
```

2024-11-18 14:10 UTC, levxyca commented
@thenicolau consegue dar um update com base nos comentários do @george-gca? 🫂

2024-11-22 21:24 UTC, thenicolau commented
> @thenicolau consegue dar um update com base nos comentários do @george-gca? 🫂

feito ✔️

2024-12-02 20:52 UTC, levxyca approved these changes
Thanks 🥰 Obrigada por contribuir!

2024-12-02 20:52 UTC, merged