feat: melhorando e dando exemplo de polimorfismo
levxyca/diciotech pull request #254
Opened 2024-10-25 01:50 UTC by thenicolau

## Descrição de PR

Melhorando e dando exemplo de polimorfismo

### Issue relacionado

#234 

## Motivações

### Informações adicionais

2024-11-12 18:55 UTC, levxyca requested changes

2024-11-12 18:55 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "O polimorfismo permite que objetos de diferentes tipos se comportem de maneira semelhante através de uma interface compartilhada."
Eu curti, mas ainda deixaria a parte final antes do exemplo para dar um pouco mais de contexto, o que acha?

```suggestion
      "description": "O polimorfismo permite que objetos de diferentes tipos se comportem de maneira semelhante através de uma interface compartilhada, embora cada tipo possa responder de uma forma própria."
```

2024-11-12 22:16 UTC, thenicolau commented on assets/data/cards_pt-br.json
> +      "description": "O polimorfismo permite que objetos de diferentes tipos se comportem de maneira semelhante através de uma interface compartilhada."
acho uma boa ideia, responde uma possivel duvida que possa surgir ao ler sobre polimorfismo

2024-11-18 14:31 UTC, levxyca approved these changes
🚀

2024-12-02 20:53 UTC, levxyca approved these changes

2024-12-02 20:53 UTC, merged