feat: simplicando termos de linguagens
levxyca/diciotech pull request #255
Opened 2024-10-25 01:59 UTC by thenicolau

## Descrição de PR

Melhorando definições de algumas linguagens

### Issue relacionado

- #228 /

## Motivações

### Informações adicionais

2024-11-07 15:49 UTC, levxyca requested changes
Concordo com o feedback do @george-gca!

2024-11-07 18:16 UTC, thenicolau commented
dei uma incrementada em exemplos de aplicacoes para ambas as linguagens

2024-11-18 14:05 UTC, levxyca approved these changes
Boa, obrigada pela contribuição 🚀

2024-11-18 14:06 UTC, merged

2024-11-18 14:31 UTC, george-gca commented
Foi mal, não parei pra reanalisar a PR.