Novos termos DevOps adicionados
levxyca/diciotech pull request #266
Opened 2024-11-13 18:05 UTC by devsnasnuvens

## Descrição de PR

Neste PR adicionei termos relacionados a infraestrutura como código (IaC) e estratégias de deployment comuns quando adotamos DevOps. Também adicionei o termo Balanceador de carga (pois fiz referência ao mesmo em uma das estratégias de deployment que defini).

## Motivações

Achei o projeto bacana e gostaria de colaborar com um pouco do conhecimento que tenho sobre DevOps :)

2024-12-02 20:50 UTC, levxyca requested changes
Obrigada pela sua contribuição 🥰 Deixei algumas ideias e comentários, veja o que acha!

2024-12-02 20:50 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Um balanceador de carga (do inglês Load Balancer) é uma ferramenta utilizada para distribuir a carga (de requisições dos usuários, por exemplo) entre múltiplos servidores. O obj
Ótima iniciativa em explicar o conceito de balanceador de carga! A explicação já está clara, mas acredito que podemos deixá-la ainda mais didática para quem talvez não esteja familiarizado com o tema. Por exemplo, você pode incluir uma analogia simples, como comparar o balanceador de carga a uma fila de caixa em um supermercado, onde várias pessoas são direcionadas para diferentes caixas para evitar espera em um único ponto. Além disso, mencionar exemplos práticos do dia a dia, como 'grandes sites de e-commerce ou plataformas de streaming', pode ajudar a contextualizar o uso.

Que tal reescrever o texto com essas sugestões? Assim, podemos garantir que qualquer pessoa, mesmo sem experiência técnica, consiga entender facilmente.

2024-12-02 20:50 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "O blue-green deployment é uma estratégia de deployment que consiste em ter um ambiente extra que replica todas as configurações do ambiente produtivo. As novas versões de softwa
A explicação sobre blue-green deployment está bem detalhada, ótimo trabalho! Para torná-la ainda mais fácil de entender, que tal simplificar um pouco e incluir um exemplo prático? Por exemplo, podemos comparar os ambientes blue e green com dois restaurantes idênticos: você prepara as mudanças em um restaurante vazio (green) enquanto o outro (blue) atende os clientes. Quando o green está pronto, você só muda os clientes para lá, garantindo uma transição suave.

Também seria interessante reorganizar para evitar repetir termos como 'ambiente' muitas vezes seguidas, o que pode deixar a leitura mais fluida.

2024-12-02 20:50 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "O canary deployment é uma estratégia de deployment que consiste em ter um ambiente extra que replica todas as configurações do ambiente produtivo. As novas versões de software s
Aqui também acho que vale um exemplo prático 🚀

2024-12-02 20:50 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Infraestrutura como código (do inglês, Infrastructure as Code ou IaC) é a prática de se construir a infraestrutura (como recursos dentro de um provedor de nuvem) através de codi
Para torná-la ainda mais acessível, especialmente para quem não conhece o conceito, que tal incluir uma analogia?

2024-12-04 01:03 UTC, devsnasnuvens commented
Oi @levxyca ! Achei super bacana suas sugestões e vou trabalhar nelas assim que possível.
Só queria tirar uma dúvida antes: Você acha interessante adicionar essas analogias depois do conceito técnico mesmo? Ou deixar a explicação apenas a cargo da analogia em si?

2024-12-04 11:31 UTC, levxyca commented
@devsnasnuvens pode deixar após a sua explicação mesmo, como forma de complemento!

2024-12-18 22:00 UTC, devsnasnuvens commented
@levxyca Revisei os conceitos conforme você me orientou nos comentários e adicionei algumas analogias.
Se tiver mais alguma sugestão, fique à vontade para comentar :)

2024-12-21 20:19 UTC, levxyca approved these changes
Arrasou 💙

2024-12-21 20:19 UTC, merged