feat: add Git and Github
levxyca/diciotech pull request #39
Opened 2023-09-27 23:04 UTC by UlissesJunior

2023-09-28 18:12 UTC, levxyca requested changes
Muitoi obrigada pela sua contribuição 💖 Apenas gostaria de alterar o termo "desenvolvedores" para algo neutro.

2023-09-28 18:12 UTC, levxyca commented on assets/data/cards_pt-br.json
> +            "description": "O GitHub é uma plataforma de hospedagem de código-fonte baseada na web que oferece uma variedade de serviços relacionados ao controle de versão e colaboração no desenvolvi
```suggestion
            "description": "O GitHub é uma plataforma de hospedagem de código-fonte baseada na web que oferece uma variedade de serviços relacionados ao controle de versão e colaboração no desenvolvimento de software (é usado em conjunto com o Git). Ele é amplamente utilizado por pessoas desenvolvedoras de todo o mundo para armazenar, colaborar, gerenciar e controlar o código-fonte de projetos de software."
```

2023-09-29 03:55 UTC, UlissesJunior commented
Olá! 
Pode fazer a alteração sim!Acredito que fique mais inclusivo pra nossa comunidade no geral quando se usa o termo de "pessoas programadoras".

2023-09-29 12:07 UTC, levxyca approved these changes

2023-09-29 12:08 UTC, merged