new-term: Abstração
levxyca/diciotech pull request #58
Opened 2023-10-01 14:49 UTC by romhenri

Olá, gostei bastante da proposta do projeto e estou muito animado para poder contribuir. Esse é o primeiro commit, onde proponho o termo "Abstração" por considera-lo fundamental para entendimento profundo do que é programação.

2023-10-05 12:17 UTC, levxyca reviewed
Muito obrigada pela sua contribuição 🤩 deixei uma sugestão, veja o que acha!

2023-10-05 12:17 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "description": "Abstração pode ser interpretada como uma simplificação da explicação de alguma ação, processo ou funcionamento visando facilitar sua compreensão e/ou uso. Em todo momento na pro
Tenho uma sugestão, veja o que acha :) tentei simplificar um pouco mais mantendo a essência do que você escreveu!

```suggestion
      "description": "Abstração é como um "atalho" que usamos para entender ou fazer algo de maneira mais fácil. Na programação, usamos abstrações o tempo todo. Isso significa que não precisamos entender todos os detalhes técnicos profundos para escrever código - como o funcionamento interno de um computador. Em vez disso, podemos usar ideias mais simples para criar nossos programas.",
```

2023-10-07 12:08 UTC, romhenri commented on assets/data/cards_pt-br.json
> +      "description": "Abstração pode ser interpretada como uma simplificação da explicação de alguma ação, processo ou funcionamento visando facilitar sua compreensão e/ou uso. Em todo momento na pro
Oi, acredito que "atalho" é um termo inadequado para descrever, pois Abstração não seria um "caminho", é muito mais como uma visão ou forma de lidar.

Alguns professores na faculdade, descrevem como uma "camada" abstrata imaginária que serve de apoio para compreensão geral.

2023-10-07 12:18 UTC, romhenri commented
O que você acha agora?

2023-10-07 14:40 UTC, levxyca approved these changes
Show de bola, muito obrigada por contribuir!

2023-10-07 14:42 UTC, levxyca requested changes
Aqui está vermelhinho como se tivesse apagado, vê se foi certinho, por favor? De resto, a explicação tá show!

<img width="870" alt="image" src="https://github.com/levxyca/diciotech/assets/19956731/d8c98a72-746d-4361-8561-ef288ed6eabc">

2023-10-07 15:43 UTC, romhenri reviewed
Realmente, estranhamente está com o sublinhado vermelho, mas não houve exclusão.

Agradeço a oportunidade de contribuir : )

2023-10-07 16:05 UTC, levxyca approved these changes

2023-10-07 16:05 UTC, merged