feat: Adicionei termos relacionados a programação baixo nivel e linguagens do tipo
levxyca/diciotech pull request #67
Opened 2023-10-05 00:16 UTC by Ryrden

Pull request relacionado a issue #66

2023-10-07 12:21 UTC, levxyca approved these changes
Obrigada por contribuir ✨

2023-10-07 12:37 UTC, Ryrden commented
@levxyca feito! pode revisar por favor?

2023-10-07 22:06 UTC, Ryrden reviewed
acabei adicionado tags a 2 definições que estavam sem tag no merge

2023-10-10 00:20 UTC, levxyca requested changes
Adicionei dois comentários para adição de vírgula para não quebrar o site em produção e adicionei alguns alterações/remoções de tags! Estamos trabalhando na documentação para deixar essa parte das tags mais transparente e simplificada para as pessoas contribuidoras mas a ideia é ter uma lista de tags padrão e usar a busca quando for algo específico.

Muito obrigada por contribuir 💖

2023-10-10 00:20 UTC, levxyca commented on assets/data/cards_pt-br.json
O deploy não tá rolando, provavelmente tem alguma vírgula sobrando/faltando por aqui.
![image](https://github.com/levxyca/diciotech/assets/19956731/58468771-1c3b-44c7-a0fc-b8481eb06a96)

2023-10-10 00:20 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "tags": ["Conceito", "JavaScript"]
```suggestion
      "tags": ["Conceito"]
```

2023-10-10 00:20 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "tags": ["Conceito", "C (Linguagem de programação)"]
```suggestion
      "tags": ["Conceito"]
```

2023-10-10 00:20 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "tags": ["Conceito", "C (Linguagem de programação)"]
```suggestion
      "tags": ["Conceito"]
```

2023-10-10 00:20 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "tags": ["C (Linguagem de programação)"]
```suggestion
      "tags": ["Conceito"]
```

2023-10-10 00:20 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "tags": ["C++"]
```suggestion
      "tags": ["Conceito"]
```

2023-10-10 00:20 UTC, levxyca commented on assets/data/cards_pt-br.json
>        "description": "É um framework do Javascript baseado no React para desenvolvimento de aplicativos móveis multiplataforma."
Achei, faltou a vírgula aqui.
```suggestion
      "description": "É um framework do Javascript baseado no React para desenvolvimento de aplicativos móveis multiplataforma.",
```

2023-10-10 00:20 UTC, levxyca commented on assets/data/cards_pt-br.json
>        "description": "É quando a gente primeiro pensa nos celulares e depois nos computadores na hora de fazer um site."
Faltou a vírugla aqui também.
```suggestion
      "description": "É quando a gente primeiro pensa nos celulares e depois nos computadores na hora de fazer um site.",
```

2023-10-10 00:20 UTC, levxyca commented
Antes de fazer as correções, não esquece de atualizar a branch também @Ryrden!

2023-10-10 03:33 UTC, Ryrden reviewed
commitei suas sugestoes

2023-10-10 03:33 UTC, Ryrden commented
> Antes de fazer as correções, não esquece de atualizar a branch também @Ryrden!

Eita, beleza. vi que ta dificil mergear isso aqui, ta sempre atualizando e n deixa sem resolver os conflitos

2023-10-10 03:36 UTC, Ryrden commented
Acha necessário q eu dê um squash nos ultimos commits em um só de fix requested changes? acabei de ver q ficou um monte, vc pode transformar o PR em um squash tmb (parece melhor)

2023-10-10 12:02 UTC, levxyca approved these changes
Tá show @Ryrden! Infelizmente, como tem muita coisa acontecendo ao mesmo tempo (por exemplo, estamos com 8 PR's abertos agora), vai acabar gerando conflitos toda vez que adicionar um ternmo mesmo 🫂 acho que só vale a atenção da minha parte pra sempre verificar se tá tudo ok e tal.

2023-10-10 12:03 UTC, merged