docs(CONTRIBUTING): atualiza a documentação de contribuição para atender tags
levxyca/diciotech pull request #71
Opened 2023-10-05 22:17 UTC by rwietter

# O que esse PR muda:

Atualiza o [CONTRIBUTING.md](https://github.com/levxyca/diciotech/blob/main/CONTRIBUTING.md) para atender a nova feature de filtro por tags e adiciona a orientação para sugerir novas tags. Minha sugestão, caso o número de tags aumente substancialmente, seria usar o elemento `details` do HTML.

## Issue relacionada

Este pull request resolve a issue #70.

2023-10-07 12:26 UTC, levxyca requested changes
Muito obrigada por contribuir 🤩 só gostaria de uma mudanças pequena em alterar o "um" para "uma" e tá aprovado!

2023-10-07 12:26 UTC, levxyca commented on CONTRIBUTING.md
> +**Observação: caso a sua contribuição não se alinhe com qualquer uma das tags disponíveis ou deseje propor uma nova tag, você pode apresentar uma sugestão por meio do envio de um [issue](https://gith
```suggestion
**Observação: caso a sua contribuição não se alinhe com qualquer uma das tags disponíveis ou deseje propor uma nova tag, você pode apresentar uma sugestão por meio do envio de uma [issue](https://github.com/levxyca/diciotech/issues) para que possamos abrir uma discussão a respeito.**

```

2023-10-07 14:02 UTC, rwietter commented on CONTRIBUTING.md
> +**Observação: caso a sua contribuição não se alinhe com qualquer uma das tags disponíveis ou deseje propor uma nova tag, você pode apresentar uma sugestão por meio do envio de um [issue](https://gith
Perfeito, resolvido!

2023-10-08 02:07 UTC, rwietter commented
O PR #77 adiciona um `id` como parte da estrutura do card. Posso incluir neste PR já isso, caso o PR #77 venha a ser incluído desta forma na branch main.

2023-10-10 00:22 UTC, levxyca commented
> O PR #77 adiciona um `id` como parte da estrutura do card. Posso incluir neste PR já isso, caso o PR #77 venha a ser incluído desta forma na branch main.
> 
> Analisando isso, talvez seja um problema ter o `id` sequencial pois quando alguém for sugerir um novo termo, terá que olhar qual o último `id` em [`cards_pt-br.json`](https://github.com/levxyca/diciotech/blob/main/assets/data/cards_pt-br.json), além de que pode ocorrer conflito de `ids`, se houver pr com `id` que já existe, aí teria que ficar checando isso também.

@rwietter tivemos esse outro PR também para refatorar isso, veja o que acha #87

2023-10-10 12:06 UTC, levxyca approved these changes
Obrigada pela contribuição!

2023-10-10 12:06 UTC, merged