Add React, componentes e propriedades
levxyca/diciotech pull request #90
Opened 2023-10-10 13:15 UTC by madalena-rocha

Adicionei as definições de React, componentes e propriedades ao dicionário.

Closes #84

2023-10-13 14:38 UTC, levxyca requested changes
Muito obrigada por contribuir 🥳 deixei alguns comentários, qualquer dúvida pode me chamar :)

2023-10-13 14:38 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "tags": ["Conceito", "React"]
Acho que aqui vale generalizar visto que o conceito de componentes não é algo exclusivo do react. O que acha?

2023-10-13 14:38 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "tags": ["Conceito", "React"]
Nesse caso, acho válido especificar melhor, o nome propriedade é muito vago. Também seria legal colocar um exemplo de que informações podem ser essas.

2023-10-13 14:38 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "tags": ["Conceito", "React"]
```suggestion
      "tags": ["Conceito"]
```

2023-10-13 14:38 UTC, levxyca commented on assets/data/cards_pt-br.json
> +      "tags": ["Conceito", "React"]
```suggestion
      "tags": ["Conceito"]
```

2023-10-14 12:08 UTC, madalena-rocha commented
Obrigada pelos comentários! Tentei seguir suas sugestões e estou disponível para mais ajustes, se necessário. Sua ajuda é muito apreciada!

2023-10-16 12:11 UTC, levxyca approved these changes

2023-10-16 12:13 UTC, merged